name: tutorial1
on: push

jobs:
    job1:
        name: job1
        runs-on: unbuntu-latest
        steps:
        - name: step1
          run: echo "Hello from job1"

    job2:
        name: job2
        runs-on: windows-latest
        steps:
        - name: step2
          run: echo today: $(Get-Date -Format yyyy-MM-dd)


    job3:
        name: job3
        runs-on: unbuntu-latest
        steps:
        - name: step3
          run: echo "Hello from job4"